### ISSUE TITLE
look deeper into Seqera free options

### ISSUE THREAD

**Issue by shellywanamaker** [Resilience-Biomarkers-for-Aquaculture/Resilience-Biomarkers-for-Aquaculture.github.io#3]

**Comment by journeymansix** [comment]
https://docs.seqera.io/platform/24.2/getting-started/deployment-options
[Seqera Cloud](https://cloud.seqera.io/) has a free tier with a limit of five concurrent workflow runs per user. Seqera Cloud Pro offers unlimited runs, dedicated support, and more.

It seems they expect you to create a compute environment right away:
> Platform web-based UI
> - Create an account and log in to Seqera Cloud at [cloud.seqera.io](https://cloud.seqera.io/).
> - **Create and configure a new [compute environment](https://docs.seqera.io/platform/24.2/compute-envs/overview).**
> - Start [launching pipelines](https://docs.seqera.io/platform/24.2/launch/launchpad).

(More to come)
