### ISSUE TITLE
explore Seqera organization and collab options

### ISSUE THREAD

**Issue by shellywanamaker** [Resilience-Biomarkers-for-Aquaculture/Resilience-Biomarkers-for-Aquaculture.github.io#5]

**Comment by shellywanamaker** [comment]
what are the limitations of organization?

**Comment by shellywanamaker** [comment]
what are the benefits of an organization?

**Comment by journeymansix** [comment]
Organizations docs:
https://docs.seqera.io/platform/24.2/orgs-and-teams/organizations
https://docs.seqera.io/platform/24.2/orgs-and-teams/workspace-management
There are several sub-entities under Organizations:
Members. I've asked for clarification whether a User needs an individual account before they can be added as an Organization member. I think a User can be a Member of more than one Organization, so I'm guessing the answer is Yes. I could try adding one of you so you can see what happens.
Workspaces (there can be multiple), which have Participants. Here, they can share compute environments and results
Teams, which have Members. I think these are just for administration. It sounds like a complication that we don't need.

Collaborators are Users who aren't Members, but have some limited access (not sure what yet).

**Comment by journeymansix** [comment]
My Seqera contact Cooper Lalonde replied to my question about whether individual accounts can be added to Organizations:
> [Yes] You can add them [even] if they already have a Seqera individual account. I’ve attached a screen recording where my colleague created a test organization (sandbox-org) and then added Paolo, who has a Gmail address. The admin user just needs to know their _email or Seqera Platform username_.

I'll close this issue as complete. @shellywanamaker and @emmastrand , how about if I create an Organization and then (1) I'll invite you Shelly by email, and (2) Emma, you create an individual account on Seqera, and then I'll add you using your username, and we can compare the two experiences?
